### ISSUE TITLE
linux环境下编译通不过..

### ISSUE THREAD

**Issue by Zephylaci** [stbui/yqb#1]
windows下能正常起..linux 安装会提示某个模块太久改名了..直接运行会提示没有es2015模块..但装2015模块会发现好像写法太古旧还是版本太老导致改名..总之就是起不来..

**Comment by Zephylaci** [comment]
倒腾了一下，通过倒是通过了..但是文件读不出来，目录可以读到，随便点了一个看起来好像是  / 的问题...

**Comment by Zephylaci** [comment]
另外高级模式那个Bash展示不符合预期...基本的指令比如CD都不认识..

**Comment by stbui** [comment]
依赖的thinkjs框架已经更新版本了，该项目已经没有更新了

**Comment by stbui** [comment]
```
npm run compile
npm run start
```

**Comment by Zephylaci** [comment]
提个小BUG..
src/controller/explorer.js 220行左右
getPath 如果获取的是相对路径会报错..
我在那个加了个替换..
        if(path.indexOf('\\')!==-1){
            path=path.replace('\\','/')
        }
就是这种的..但总感觉不是很健壮..先提出来吧

**Comment by Zephylaci** [comment]
转译了..字符串里是'\\'里面是两个..打不出来

**Comment by Zephylaci** [comment]
再问一个..编辑器菜单里那些文件编辑啥的..都是假的么？有办法扩展么...

**Comment by Zephylaci** [comment]
另外猛然发现..前进后退这类功能看起来是假的..目录地址到时变了..但是调的却是this.success()？能看到这是一个弹窗..就是不知道在哪定义的..

**Comment by Zephylaci** [comment]
又遇到一个奇怪的BUG..某个项目二级文件夹别的都没问题..但是build点进去就进不去..我去日志里看了下..发现变成了..XXXXX/build/build/ 其它的都没事..怪哉..
其它..看了下修改右侧的默认项目..似乎是通过配置文件实现的..略不人性化....
构建工具也不敢乱点..搞不清楚哪个会出问题..

**Comment by stbui** [comment]
这仅仅是个实验项目，功能缺失。二次开发还是不要做了

**Comment by Zephylaci** [comment]
好吧...那么我想问问作者..我想找一个好点的基于Node的文件操作库..功能和这个项目的文件操作类似那种..有推荐么?目前我找到的大都是静态文件展示...h5ai是基于php的...
